### ISSUE TITLE
Connection Error 

### ISSUE THREAD

**Issue by rishabhwadhwa15** [aznamier/keycloak-event-listener-rabbitmq#36]
I have deployed this plugin inside keycloak but its giving me connection error 
ERROR [com.github.aznamier.keycloak.event.provider.RabbitMqEventListenerProviderFactory] (executor-thread-4) keycloak-to-rabbitmq ERROR on connection to rabbitmq: java.net.ConnectException: Connection refused (Connection refused)
        at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:412)
        at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:255)
        at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:237)
        at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.base/java.net.Socket.connect(Socket.java:609)
        at com.rabbitmq.client.impl.SocketFrameHandlerFactory.create(SocketFrameHandlerFactory.java:60)
        at com.rabbitmq.client.impl.recovery.RecoveryAwareAMQConnectionFactory.newConnection(RecoveryAwareAMQConnectionFactory.java:63)
        at com.rabbitmq.client.impl.recovery.AutorecoveringConnection.init(AutorecoveringConnection.java:160)
        at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:1216)
        at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:1173)
        at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:1131)
        at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:1294)
        at com.github.aznamier.keycloak.event.provider.RabbitMqEventListenerProviderFactory.checkConnectionAndChannel(RabbitMqEventListenerProviderFactory.java:32)
        at com.github.aznamier.keycloak.event.provider.RabbitMqEventListenerProviderFactory.create(RabbitMqEventListenerProviderFactory.java:25)
        at com.github.aznamier.keycloak.event.provider.RabbitMqEventListenerProviderFactory.create(RabbitMqEventListenerProviderFactory.java:15)
        at org.keycloak.services.DefaultKeycloakSession.getProvider(DefaultKeycloakSession.java:282)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.jboss.resteasy.core.ContextParameterInjector$GenericDelegatingProxy.invoke(ContextParameterInjector.java:166)
        at com.sun.proxy.$Proxy56.getProvider(Unknown Source)
        
        
        Its not running on local as well even after providing all correct values . What could be the issue , please help ?

**Comment by opexu** [comment]
Connection errors i fixed using 3.03 and set
KK_TO_RMQ_PORT: 5672
KK_TO_RMQ_VHOST: /

**Comment by BenoitPE** [comment]
Hello, I encountered the same problem, has anyone found a solution to this problem?

I'm running Keycloak and RabbitMQ with docker-compose:
```yaml
version: '3'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:21.1.2
    container_name: keycloak
    restart: unless-stopped
    command: ["start-dev"]
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: yourdb
      KC_DB_URL_DATABASE: keycloak
      KC_DB_PASSWORD: password
      KC_DB_USERNAME: keycloak
      KC_DB_SCHEMA: public
      KC_HTTP_RELATIVE_PATH: /auth
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KK_TO_RMQ_URL: localhost
      KK_TO_RMQ_VHOST: /
      KK_TO_RMQ_PORT: 5672
      KK_TO_RMQ_EXCHANGE: amq.topic
      KK_TO_RMQ_USERNAME: guest
      KK_TO_RMQ_PASSWORD: guest

    ports:
      - 8080:8080
    volumes:
      - ./keycloak-to-rabbit-3.0.5.jar:/opt/keycloak/providers/keycloak-to-rabbit-3.0.5.jar
    depends_on:
      yourdb:
        condition: service_healthy
    networks:
      keycloak:

  yourdb:
    container_name: yourdb
    image: postgres:16.0-bullseye
    restart: unless-stopped
    command: postgres -c 'max_connections=200'
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    healthcheck:
      test: "exit 0"
    ports:
      - "5436:5432"
    networks:
      keycloak:

  rabbitmq:
    image: rabbitmq:3.13.1-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    networks:
      keycloak:

networks:
  keycloak:
    driver: bridge
```

![image](https://github.com/aznamier/keycloak-event-listener-rabbitmq/assets/60927544/60b94891-2074-413e-8231-9c3d869ca71a)

Thanks a lot
